### ISSUE TITLE
No working on High Sierra

### ISSUE THREAD

**Issue by m3ir** [gmarnin/Profiles#1]
cause of SIP?

**Comment by gmarnin** [comment]
What's not working?

**Comment by m3ir** [comment]
sorry :)
Airport Menubar Disable.mobileconfig not removing the Wifi icon on High Sierra

**Comment by gmarnin** [comment]
Disabling still works. The `Disable-Wifi-1.0.mobileconfig` profile is only set to disable wifi, not remove the icon. I haven't tested removing.

**Comment by m3ir** [comment]
Right, Disable-Wifi-1.0.mobileconfig works fine on High Sierra.
the only problem is with Airport Menubar Disable.mobileconfig, actually you can edit the mcx and remove any toher icons but WiFi .
